name: Test on Chrome

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress testsi
      - name: Unit tests
	uses: mattallty/jest-github-action@v1
	env:
	  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
	with:
	  test-command: "npm run test:coverage"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          #build: npm run build
          start: npm start
          browser: chrome
          headless: true
