name: Test on Chrome

on: push

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install dependencies
        run: npm ci
      - name: UnitTests
        uses: mattallty/jest-github-action@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          test-command: "npm run test:coverage"
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          start: npm start
          browser: chrome
          headless: true
